import json
import re
from collections import Counter
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "third_party/webarena/config_files/test.raw.json"
OUT = ROOT / "lk47/intents/templates_data.py"
VERIFIED_SRC = ROOT / "third_party/webarena-verified/webarena-verified.json"
VERIFIED_OUT = ROOT / "lk47/intents/templates_verified.py"
SLOT = re.compile(r"\{\{(.+?)\}\}")


def _original_name(name: str, pairs: list[tuple[dict[str, Any], dict[str, Any]]]) -> str | None:
    # the original slot that holds the same value in most tasks of the template; the plans read
    # slots by their original names
    votes: Counter[str] = Counter()
    for verified, original in pairs:
        value = str(verified[name]).strip().lower()
        votes.update(o for o, v in original.items() if str(v).strip().lower() == value)
    if not votes:
        return name if any(name in original for _, original in pairs) else None
    return max(votes, key=lambda o: (votes[o], o == name))


def verified() -> None:
    with open(SRC) as f:
        original = {t["task_id"]: t for t in json.load(f)}
    with open(VERIFIED_SRC) as f:
        tasks = json.load(f)
    by_template: dict[tuple[int, str], list[tuple[dict[str, Any], dict[str, Any]]]] = {}
    for t in tasks:
        text = re.sub(r"\{% for \w+ in (\w+) %\}.*?\{% endfor %\}", r"{{\1}}", t["intent_template"])
        key = (t["intent_template_id"], text)
        pair = (t["instantiation_dict"], original[t["task_id"]]["instantiation_dict"])
        by_template.setdefault(key, []).append(pair)
    lines = [
        "# Generated by scripts/gen_templates.py from webarena-verified.json. Do not edit.",
        "",
        "# (template id, wording, ((slot, the original slot it fills or None), ...))",
        "VERIFIED_TEMPLATES: tuple[tuple[int, str, tuple[tuple[str, str | None], ...]], ...] = (",
    ]
    unmapped = 0
    for (tid, text), pairs in sorted(by_template.items()):
        slots = tuple((s, _original_name(s, pairs)) for s in dict.fromkeys(SLOT.findall(text)))
        left = [s for s, o in slots if o is None]
        free = set.intersection(*(set(original) for _, original in pairs)) - {o for _, o in slots}
        if len(left) == 1 and len(free) == 1:
            slots = tuple((s, free.pop() if o is None else o) for s, o in slots)
        unmapped += sum(o is None for _, o in slots)
        lines.append(f"    ({tid}, {text!r}, {slots!r}),")
    lines.append(")")
    lines.append("")
    VERIFIED_OUT.write_text("\n".join(lines))
    print(
        f"verified template_texts={len(by_template)} unmapped_slots={unmapped} "
        f"wrote={VERIFIED_OUT.relative_to(ROOT)}"
    )


def main() -> None:
    with open(SRC) as f:
        tasks = json.load(f)
    # a template id groups near-duplicate wordings; the grammar needs every wording
    pairs = sorted({(t["intent_template_id"], t["intent_template"]) for t in tasks})
    lines = [
        "# Generated by scripts/gen_templates.py from test.raw.json. Do not edit.",
        "",
        "TEMPLATES: tuple[tuple[int, str, tuple[str, ...]], ...] = (",
    ]
    for tid, text in pairs:
        lines.append(f"    ({tid}, {text!r}, {tuple(SLOT.findall(text))!r}),")
    lines.append(")")
    lines.append("")
    OUT.write_text("\n".join(lines))
    ids = {tid for tid, _ in pairs}
    names = {s for _, text in pairs for s in SLOT.findall(text)}
    print(
        f"template_ids={len(ids)} template_texts={len(pairs)} slot_names={len(names)} "
        f"wrote={OUT.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
    verified()
